
export default {
  fallback: {
    executable: "application-x-executable-symbolic",
    notification: "mail-mark-important-symbolic",
    video: "video-display-symbolic",
    audio: "audio-speakers-symbolic",
  },
  ui: {
    password: "auth-fingerprint-symbolic",
    keyboard: "input-keyboard-symbolic",
    close: "window-close-symbolic",
    colorpicker: "color-select-symbolic",
    info: "info-symbolic",
    link: "external-link-symbolic",
    lock: "system-lock-screen-symbolic",
    menu: "open-menu-symbolic",
    refresh: "view-refresh-symbolic",
    search: "system-search-symbolic",
    settings: "emblem-system-symbolic",
    themes: "applications-graphics-symbolic",
    tick: "",
    time: "hourglass-symbolic",
    toolbars: "toolbars-symbolic",
    warning: "dialog-warning-symbolic",
    person: "person-symbolic",
    arrow: {
      right: "pan-end-symbolic",
      left: "pan-start-symbolic",
      down: "pan-down-symbolic",
      up: "pan-up-symbolic",
    },
  },
  audio: {
    microphone: {
      muted: "microphone-disabled-symbolic",
      low: "microphone-sensitivity-low-symbolic",
      medium: "microphone-sensitivity-medium-symbolic",
      high: "microphone-sensitivity-high-symbolic",
    },
    speaker: {
      muted: "audio-volume-muted-symbolic",
      low: "audio-volume-low-symbolic",
      medium: "audio-volume-medium-symbolic",
      high: "audio-volume-high-symbolic",
      overamplified: "audio-volume-overamplified-symbolic",
    },
    type: {
      headset: "audio-headphones-symbolic",
      speaker: "audio-speakers-symbolic",
      card: "audio-card-symbolic",
    },
    mixer: "mixer-symbolic",
    player: "multimedia-player-symbolic",
  },
  battery: {
    full: "battery-empty-symbolic",
    warning: "battery-empty-symbolic",
  },
  bluetooth: {
    enabled: "bluetooth-active-symbolic",
    disabled: "bluetooth-disabled-symbolic",
  },
  brightness: {
    indicator: "display-brightness-symbolic",
    keyboard: "keyboard-brightness-symbolic",
    screen: "display-brightness-symbolic",
  },
  powermenu: {
    sleep: "weather-clear-night-symbolic",
    reboot: "system-reboot-symbolic",
    logout: "system-log-out-symbolic",
    shutdown: "system-shutdown-symbolic",
    lock: "system-lock-screen-symbolic",
  },
  recorder: {
    recording: "media-record-symbolic",
  },
  notifications: {
    noisy: "org.gnome.Settings-notifications-symbolic",
    silent: "notifications-disabled-symbolic",
    message: "chat-bubbles-symbolic",
  },
  trash: {
    full: "user-trash-full-symbolic",
    empty: "user-trash-symbolic",
  },
  mpris: {
    shuffle: {
      enabled: "media-playlist-shuffle-symbolic",
      disabled: "media-playlist-consecutive-symbolic",
    },
    loop: {
      none: "media-playlist-repeat-symbolic",
      track: "media-playlist-repeat-song-symbolic",
      playlist: "media-playlist-repeat-symbolic",
    },
    playing: "media-playback-pause-symbolic",
    paused: "media-playback-start-symbolic",
    stopped: "media-playback-start-symbolic",
    prev: "media-skip-backward-symbolic",
    next: "media-skip-forward-symbolic",
  },
  system: {
    cpu: "org.gnome.SystemMonitor-symbolic",
    ram: "drive-harddisk-solidstate-symbolic",
    temp: "temperature-symbolic",
  },
  color: {
    dark: "dark-mode-symbolic",
    light: "light-mode-symbolic",
  },
  network: {
    wired: {
      connected: "network-wired-symbolic",
      portal: "network-wired-acquiring-symbolic",
      limited: "network-wired-no-route-symbolic",
      disconnected: "network-wired-acquiring-symbolic",
    },
  },
  screenshot: {
    desktop: "preferences-desktop-display-symbolic",
    region: "edit-cut-symbolic",
    window: "edit-copy-symbolic",
  },
  weather: {
    "1": "weather-clear-symbolic",
    "2": "weather-few-clouds-symbolic",
    "3": "weather-few-clouds-symbolic",
    "4": "weather-few-clouds-symbolic",
    "5": "weather-clear-symbolic",
    "6": "weather-few-clouds-symbolic",
    "7": "weather-overcast-symbolic",
    "8": "weather-overcast-symbolic",
    "11": "weather-windy-symbolic",
    "12": "weather-showers-symbolic",
    "13": "weather-showers-symbolic",
    "14": "weather-showers-symbolic",
    "15": "weather-storm-symbolic",
    "16": "weather-storm-symbolic",
    "17": "weather-storm-symbolic",
    "18": "weather-showers-symbolic",
    "19": "weather-overcast-symbolic",
    "20": "weather-few-clouds-symbolic",
    "21": "weather-few-clouds-symbolic",
    "22": "weather-snow-symbolic",
    "23": "weather-snow-symbolic",
    "24": "weather-snow-symbolic",
    "25": "weather-snow-symbolic",
    "26": "weather-snow-symbolic",
    "29": "weather-snow-symbolic",
    "33": "weather-clear-night-symbolic",
    "34": "weather-few-clouds-night-symbolic",
    "35": "weather-few-clouds-night-symbolic",
    "36": "weather-few-clouds-night-symbolic",
    "37": "weather-clear-night-symbolic",
    "38": "weather-overcast-symbolic",
    "39": "weather-overcast-symbolic",
    "40": "weather-overcast-symbolic",
    "41": "weather-showers-symbolic",
    "42": "weather-storm-symbolic",
    "43": "weather-snow-symbolic",
    "44": "weather-snow-symbolic",
  },
};
